version: '3'

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=your_uri_here

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  jenkins:
    image: jenkins/jenkins:lts
    network_mode: "host"
    
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:community
    ports:
      - "9001:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  jenkins_home:
