apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-frontend
  template:
    metadata:
      labels:
        app: smart-frontend
    spec:
      containers:
      - name: frontend
        image: sowbagya15/smart-farmer-frontend
        ports:
        - containerPort: 80
